-- Datos iniciales: EPS / aseguradoras y medicamentos frecuentes
SET NAMES utf8mb4;

INSERT IGNORE INTO eps (nombre) VALUES
('Nueva EPS'),
('EPS Sanitas'),
('EPS Sura'),
('Salud Total EPS'),
('Compensar EPS'),
('Famisanar EPS'),
('Coosalud EPS'),
('Mutual Ser EPS'),
('Asmet Salud EPS'),
('Emssanar EPS'),
('Savia Salud EPS'),
('Capital Salud EPS'),
('Cajacopi EPS'),
('Comfenalco Valle EPS'),
('Servicio Occidental de Salud (SOS)'),
('Aliansalud EPS'),
('Capresoca EPS'),
('Pijaos Salud EPSI'),
('Anas Wayuu EPSI'),
('Dusakawi EPSI'),
('Mallamas EPSI'),
('Comfachocó EPS'),
('Comfaoriente EPS'),
('Salud Mía EPS'),
('Fuerzas Militares (Régimen especial)'),
('Policía Nacional (Régimen especial)'),
('Magisterio - FOMAG (Régimen especial)'),
('Ecopetrol (Régimen especial)'),
('SOAT / Aseguradora'),
('ARL'),
('Medicina prepagada'),
('Particular');

INSERT INTO medicamentos (nombre, concentracion, forma_farmaceutica) VALUES
('Acetaminofén', '500 mg', 'Tableta'),
('Acetaminofén', '150 mg/5 mL', 'Jarabe'),
('Ibuprofeno', '400 mg', 'Tableta'),
('Ibuprofeno', '800 mg', 'Tableta'),
('Ibuprofeno', '100 mg/5 mL', 'Suspensión oral'),
('Naproxeno', '250 mg', 'Tableta'),
('Diclofenaco sódico', '50 mg', 'Tableta'),
('Diclofenaco sódico', '75 mg/3 mL', 'Solución inyectable'),
('Dipirona (metamizol)', '500 mg', 'Tableta'),
('Ketorolaco', '30 mg/mL', 'Solución inyectable'),
('Tramadol', '50 mg', 'Cápsula'),
('Metocarbamol', '750 mg', 'Tableta'),
('Amoxicilina', '500 mg', 'Cápsula'),
('Amoxicilina', '250 mg/5 mL', 'Suspensión oral'),
('Amoxicilina + ácido clavulánico', '875 mg/125 mg', 'Tableta'),
('Cefalexina', '500 mg', 'Cápsula'),
('Dicloxacilina', '500 mg', 'Cápsula'),
('Azitromicina', '500 mg', 'Tableta'),
('Claritromicina', '500 mg', 'Tableta'),
('Ciprofloxacino', '500 mg', 'Tableta'),
('Nitrofurantoína', '100 mg', 'Cápsula'),
('Trimetoprim + sulfametoxazol', '160 mg/800 mg', 'Tableta'),
('Metronidazol', '500 mg', 'Tableta'),
('Penicilina G benzatínica', '2.400.000 UI', 'Polvo para reconstituir'),
('Fluconazol', '150 mg', 'Cápsula'),
('Clotrimazol', '1 %', 'Crema'),
('Nistatina', '100.000 UI/mL', 'Suspensión oral'),
('Aciclovir', '800 mg', 'Tableta'),
('Albendazol', '400 mg', 'Tableta'),
('Albendazol', '200 mg/5 mL', 'Suspensión oral'),
('Ivermectina', '6 mg', 'Tableta'),
('Permetrina', '5 %', 'Crema'),
('Loratadina', '10 mg', 'Tableta'),
('Cetirizina', '10 mg', 'Tableta'),
('Clorfeniramina', '4 mg', 'Tableta'),
('Prednisolona', '5 mg', 'Tableta'),
('Prednisona', '5 mg', 'Tableta'),
('Dexametasona', '8 mg/2 mL', 'Solución inyectable'),
('Betametasona', '0,05 %', 'Crema'),
('Hidrocortisona', '1 %', 'Crema'),
('Salbutamol', '100 mcg/dosis', 'Inhalador'),
('Beclometasona', '250 mcg/dosis', 'Inhalador'),
('Bromuro de ipratropio', '20 mcg/dosis', 'Inhalador'),
('Omeprazol', '20 mg', 'Cápsula'),
('Esomeprazol', '40 mg', 'Tableta'),
('Hidróxido de aluminio + hidróxido de magnesio', '', 'Suspensión oral'),
('Metoclopramida', '10 mg', 'Tableta'),
('Hioscina N-butilbromuro', '10 mg', 'Tableta'),
('Loperamida', '2 mg', 'Tableta'),
('Sales de rehidratación oral', '', 'Sobre'),
('Lactulosa', '65 %', 'Solución oral'),
('Losartán', '50 mg', 'Tableta'),
('Enalapril', '20 mg', 'Tableta'),
('Amlodipino', '5 mg', 'Tableta'),
('Hidroclorotiazida', '25 mg', 'Tableta'),
('Metoprolol tartrato', '50 mg', 'Tableta'),
('Atorvastatina', '20 mg', 'Tableta'),
('Atorvastatina', '40 mg', 'Tableta'),
('Ácido acetilsalicílico', '100 mg', 'Tableta'),
('Metformina', '850 mg', 'Tableta'),
('Glibenclamida', '5 mg', 'Tableta'),
('Insulina glargina', '100 UI/mL', 'Solución inyectable'),
('Levotiroxina', '50 mcg', 'Tableta'),
('Sulfato ferroso', '300 mg', 'Tableta'),
('Ácido fólico', '1 mg', 'Tableta'),
('Carbonato de calcio + vitamina D', '600 mg/200 UI', 'Tableta'),
('Sertralina', '50 mg', 'Tableta'),
('Fluoxetina', '20 mg', 'Cápsula'),
('Amitriptilina', '25 mg', 'Tableta'),
('Gentamicina oftálmica', '0,3 %', 'Gotas'),
('Hipromelosa (lágrima artificial)', '0,5 %', 'Gotas'),
('Levonorgestrel', '1,5 mg', 'Tableta'),
('Levonorgestrel + etinilestradiol', '0,15 mg/0,03 mg', 'Tableta');
