-- CIE-10: diagnósticos frecuentes en medicina general.
-- La tabla completa oficial puede importarse desde Administración > CIE-10 (archivo CSV).
SET NAMES utf8mb4;

INSERT IGNORE INTO cie10 (codigo, descripcion) VALUES
('A080', 'Enteritis debida a rotavirus'),
('A09X', 'Diarrea y gastroenteritis de presunto origen infeccioso'),
('A150', 'Tuberculosis del pulmón, confirmada por hallazgo microscópico del bacilo tuberculoso en esputo'),
('A539', 'Sífilis, no especificada'),
('A630', 'Verrugas (venéreas) anogenitales'),
('A970', 'Dengue sin signos de alarma'),
('A971', 'Dengue con signos de alarma'),
('A972', 'Dengue grave'),
('B009', 'Infección debida al virus del herpes, no especificada'),
('B019', 'Varicela sin complicaciones'),
('B029', 'Herpes zóster sin complicaciones'),
('B07X', 'Verrugas víricas'),
('B24X', 'Enfermedad por virus de la inmunodeficiencia humana [VIH], sin otra especificación'),
('B349', 'Infección viral, no especificada'),
('B351', 'Tiña de las uñas'),
('B353', 'Tiña del pie [tinea pedis]'),
('B354', 'Tiña del cuerpo [tinea corporis]'),
('B356', 'Tiña inguinal [tinea cruris]'),
('B360', 'Pitiriasis versicolor'),
('B370', 'Estomatitis candidiásica'),
('B373', 'Candidiasis de la vulva y de la vagina'),
('B379', 'Candidiasis, no especificada'),
('B829', 'Parasitosis intestinal, sin otra especificación'),
('B850', 'Pediculosis debida a Pediculus humanus capitis'),
('B86X', 'Escabiosis'),
('D259', 'Leiomioma del útero, sin otra especificación'),
('D509', 'Anemia por deficiencia de hierro sin otra especificación'),
('D649', 'Anemia de tipo no especificado'),
('E039', 'Hipotiroidismo, no especificado'),
('E059', 'Tirotoxicosis, no especificada'),
('E109', 'Diabetes mellitus insulinodependiente sin mención de complicación'),
('E119', 'Diabetes mellitus no insulinodependiente sin mención de complicación'),
('E149', 'Diabetes mellitus, no especificada, sin mención de complicación'),
('E440', 'Desnutrición proteicocalórica moderada'),
('E46X', 'Desnutrición proteicocalórica, no especificada'),
('E559', 'Deficiencia de vitamina D, no especificada'),
('E660', 'Obesidad debida a exceso de calorías'),
('E669', 'Obesidad, no especificada'),
('E780', 'Hipercolesterolemia pura'),
('E781', 'Hipergliceridemia pura'),
('E782', 'Hiperlipidemia mixta'),
('E785', 'Hiperlipidemia, no especificada'),
('E790', 'Hiperuricemia sin signos de artritis inflamatoria y enfermedad tofácea'),
('E86X', 'Depleción del volumen'),
('E876', 'Hipopotasemia'),
('F100', 'Trastornos mentales y del comportamiento debidos al uso de alcohol: intoxicación aguda'),
('F171', 'Trastornos mentales y del comportamiento debidos al uso de tabaco: uso nocivo'),
('F321', 'Episodio depresivo moderado'),
('F329', 'Episodio depresivo, no especificado'),
('F410', 'Trastorno de pánico [ansiedad paroxística episódica]'),
('F411', 'Trastorno de ansiedad generalizada'),
('F412', 'Trastorno mixto de ansiedad y depresión'),
('F419', 'Trastorno de ansiedad, no especificado'),
('F432', 'Trastornos de adaptación'),
('F510', 'Insomnio no orgánico'),
('F900', 'Perturbación de la actividad y de la atención'),
('G20X', 'Enfermedad de Parkinson'),
('G309', 'Enfermedad de Alzheimer, no especificada'),
('G409', 'Epilepsia, tipo no especificado'),
('G430', 'Migraña sin aura [migraña común]'),
('G431', 'Migraña con aura [migraña clásica]'),
('G439', 'Migraña, no especificada'),
('G442', 'Cefalea debida a tensión'),
('G470', 'Trastornos del inicio y del mantenimiento del sueño [insomnios]'),
('G510', 'Parálisis de Bell'),
('G560', 'Síndrome del túnel carpiano'),
('G629', 'Polineuropatía, no especificada'),
('H000', 'Orzuelo y otras inflamaciones profundas del párpado'),
('H010', 'Blefaritis'),
('H100', 'Conjuntivitis mucopurulenta'),
('H101', 'Conjuntivitis atópica aguda'),
('H103', 'Conjuntivitis aguda, no especificada'),
('H109', 'Conjuntivitis, no especificada'),
('H527', 'Trastorno de la refracción, no especificado'),
('H609', 'Otitis externa, sin otra especificación'),
('H612', 'Cerumen impactado'),
('H650', 'Otitis media aguda serosa'),
('H660', 'Otitis media supurativa aguda'),
('H669', 'Otitis media, no especificada'),
('H811', 'Vértigo paroxístico benigno'),
('H919', 'Hipoacusia, no especificada'),
('I10X', 'Hipertensión esencial (primaria)'),
('I119', 'Enfermedad cardíaca hipertensiva sin insuficiencia cardíaca (congestiva)'),
('I209', 'Angina de pecho, no especificada'),
('I219', 'Infarto agudo del miocardio, sin otra especificación'),
('I48X', 'Fibrilación y aleteo auricular'),
('I500', 'Insuficiencia cardíaca congestiva'),
('I509', 'Insuficiencia cardíaca, no especificada'),
('I639', 'Infarto cerebral, no especificado'),
('I64X', 'Accidente vascular encefálico agudo, no especificado como hemorrágico o isquémico'),
('I839', 'Venas varicosas de los miembros inferiores sin úlcera ni inflamación'),
('I959', 'Hipotensión, no especificada'),
('J00X', 'Rinofaringitis aguda [resfriado común]'),
('J010', 'Sinusitis maxilar aguda'),
('J019', 'Sinusitis aguda, no especificada'),
('J020', 'Faringitis estreptocócica'),
('J029', 'Faringitis aguda, no especificada'),
('J030', 'Amigdalitis estreptocócica'),
('J039', 'Amigdalitis aguda, no especificada'),
('J040', 'Laringitis aguda'),
('J050', 'Laringitis obstructiva aguda [crup]'),
('J069', 'Infección aguda de las vías respiratorias superiores, no especificada'),
('J111', 'Influenza con otras manifestaciones respiratorias, virus no identificado'),
('J129', 'Neumonía viral, no especificada'),
('J159', 'Neumonía bacteriana, no especificada'),
('J189', 'Neumonía, no especificada'),
('J209', 'Bronquitis aguda, no especificada'),
('J210', 'Bronquiolitis aguda debida a virus sincitial respiratorio'),
('J219', 'Bronquiolitis aguda, no especificada'),
('J304', 'Rinitis alérgica, no especificada'),
('J310', 'Rinitis crónica'),
('J329', 'Sinusitis crónica, no especificada'),
('J40X', 'Bronquitis, no especificada como aguda o crónica'),
('J441', 'Enfermedad pulmonar obstructiva crónica con exacerbación aguda, no especificada'),
('J449', 'Enfermedad pulmonar obstructiva crónica, no especificada'),
('J450', 'Asma predominantemente alérgica'),
('J459', 'Asma, no especificada'),
('J46X', 'Estado asmático'),
('K029', 'Caries dental, no especificada'),
('K121', 'Otras formas de estomatitis'),
('K210', 'Enfermedad del reflujo gastroesofágico con esofagitis'),
('K219', 'Enfermedad del reflujo gastroesofágico sin esofagitis'),
('K259', 'Úlcera gástrica, no especificada como aguda ni crónica, sin hemorragia ni perforación'),
('K295', 'Gastritis crónica, no especificada'),
('K297', 'Gastritis, no especificada'),
('K30X', 'Dispepsia'),
('K359', 'Apendicitis aguda, no especificada'),
('K409', 'Hernia inguinal unilateral o no especificada, sin obstrucción ni gangrena'),
('K429', 'Hernia umbilical sin obstrucción ni gangrena'),
('K529', 'Colitis y gastroenteritis no infecciosas, no especificadas'),
('K580', 'Síndrome del colon irritable con diarrea'),
('K589', 'Síndrome del colon irritable sin diarrea'),
('K590', 'Constipación'),
('K602', 'Fisura anal, no especificada'),
('K649', 'Hemorroides, no especificadas'),
('K760', 'Degeneración grasa del hígado, no clasificada en otra parte'),
('K802', 'Cálculo de la vesícula biliar sin colecistitis'),
('K810', 'Colecistitis aguda'),
('K859', 'Pancreatitis aguda, no especificada'),
('L010', 'Impétigo [cualquier sitio anatómico] [cualquier organismo]'),
('L029', 'Absceso cutáneo, furúnculo y carbunco de sitio no especificado'),
('L039', 'Celulitis de sitio no especificado'),
('L209', 'Dermatitis atópica, no especificada'),
('L219', 'Dermatitis seborreica, no especificada'),
('L22X', 'Dermatitis del pañal'),
('L239', 'Dermatitis alérgica de contacto, de causa no especificada'),
('L309', 'Dermatitis, no especificada'),
('L409', 'Psoriasis, no especificada'),
('L500', 'Urticaria alérgica'),
('L509', 'Urticaria, no especificada'),
('L600', 'Uña encarnada'),
('L700', 'Acné vulgar'),
('M069', 'Artritis reumatoide, no especificada'),
('M109', 'Gota, no especificada'),
('M179', 'Gonartrosis, no especificada'),
('M199', 'Artrosis, no especificada'),
('M255', 'Dolor en articulación'),
('M419', 'Escoliosis, no especificada'),
('M511', 'Trastornos de disco lumbar y otros, con radiculopatía'),
('M542', 'Cervicalgia'),
('M544', 'Lumbago con ciática'),
('M545', 'Lumbago no especificado'),
('M546', 'Dolor en la columna dorsal'),
('M549', 'Dorsalgia, no especificada'),
('M626', 'Distensión muscular'),
('M654', 'Tenosinovitis de estiloides radial [de Quervain]'),
('M722', 'Fibromatosis de la aponeurosis plantar'),
('M750', 'Capsulitis adhesiva del hombro'),
('M751', 'Síndrome de manguito rotatorio'),
('M754', 'Síndrome de abducción dolorosa del hombro'),
('M770', 'Epicondilitis media'),
('M771', 'Epicondilitis lateral'),
('M791', 'Mialgia'),
('M796', 'Dolor en miembro'),
('M797', 'Fibromialgia'),
('M810', 'Osteoporosis postmenopáusica'),
('M819', 'Osteoporosis, no especificada'),
('N10X', 'Nefritis tubulointersticial aguda'),
('N189', 'Enfermedad renal crónica, no especificada'),
('N200', 'Cálculo del riñón'),
('N23X', 'Cólico renal, no especificado'),
('N300', 'Cistitis aguda'),
('N390', 'Infección de vías urinarias, sitio no especificado'),
('N40X', 'Hiperplasia de la próstata'),
('N644', 'Mastodinia'),
('N72X', 'Enfermedad inflamatoria del cuello uterino'),
('N739', 'Enfermedad inflamatoria pélvica femenina, no especificada'),
('N760', 'Vaginitis aguda'),
('N912', 'Amenorrea, sin otra especificación'),
('N920', 'Menstruación excesiva y frecuente con ciclo regular'),
('N943', 'Síndrome de tensión premenstrual'),
('N946', 'Dismenorrea, no especificada'),
('N951', 'Estados menopáusicos y climatéricos femeninos'),
('O13X', 'Hipertensión gestacional [inducida por el embarazo] sin proteinuria significativa'),
('O210', 'Hiperemesis gravídica leve'),
('O234', 'Infección no especificada de las vías urinarias en el embarazo'),
('R05X', 'Tos'),
('R060', 'Disnea'),
('R074', 'Dolor en el pecho, no especificado'),
('R101', 'Dolor abdominal localizado en parte superior'),
('R103', 'Dolor localizado en otras partes inferiores del abdomen'),
('R104', 'Otros dolores abdominales y los no especificados'),
('R11X', 'Náusea y vómito'),
('R12X', 'Acidez'),
('R21X', 'Salpullido y otras erupciones cutáneas no específicas'),
('R252', 'Calambre y espasmo'),
('R300', 'Disuria'),
('R31X', 'Hematuria, no especificada'),
('R42X', 'Mareo y desvanecimiento'),
('R509', 'Fiebre, no especificada'),
('R51X', 'Cefalea'),
('R529', 'Dolor, no especificado'),
('R53X', 'Malestar y fatiga'),
('R55X', 'Síncope y colapso'),
('R590', 'Adenomegalia localizada'),
('R600', 'Edema localizado'),
('R634', 'Pérdida anormal de peso'),
('R739', 'Hiperglucemia, no especificada'),
('S009', 'Traumatismo superficial de la cabeza, parte no especificada'),
('S019', 'Herida de la cabeza, parte no especificada'),
('S060', 'Concusión'),
('S134', 'Esguince y torcedura de la columna cervical'),
('S335', 'Esguince y torcedura de la columna lumbar'),
('S434', 'Esguince y torcedura de la articulación del hombro'),
('S635', 'Esguince y torcedura de la muñeca'),
('S610', 'Herida de dedo(s) de la mano, sin daño de la(s) uña(s)'),
('S836', 'Esguince y torcedura de otras partes y las no especificadas de la rodilla'),
('S934', 'Esguince y torcedura del tobillo'),
('T009', 'Traumatismos superficiales múltiples, no especificados'),
('T140', 'Traumatismo superficial de región no especificada del cuerpo'),
('T141', 'Herida de región no especificada del cuerpo'),
('T159', 'Cuerpo extraño en parte externa del ojo, sitio no especificado'),
('T16X', 'Cuerpo extraño en el oído'),
('T300', 'Quemadura de región del cuerpo no especificada, grado no especificado'),
('T634', 'Veneno de otros artrópodos'),
('T783', 'Edema angioneurótico'),
('T784', 'Alergia no especificada'),
('U071', 'COVID-19, virus identificado'),
('U072', 'COVID-19, virus no identificado'),
('Z000', 'Examen médico general'),
('Z001', 'Control de salud de rutina del niño'),
('Z003', 'Examen del estado de desarrollo del adolescente'),
('Z021', 'Examen preempleo'),
('Z025', 'Examen para la participación en deportes'),
('Z027', 'Extensión de certificado médico'),
('Z124', 'Examen de pesquisa especial para tumor del cuello uterino'),
('Z131', 'Examen de pesquisa especial para diabetes mellitus'),
('Z136', 'Examen de pesquisa especial para trastornos cardiovasculares'),
('Z300', 'Consejo y asesoramiento general sobre la anticoncepción'),
('Z304', 'Supervisión del uso de drogas anticonceptivas'),
('Z305', 'Supervisión del uso de dispositivo anticonceptivo (intrauterino)'),
('Z321', 'Embarazo confirmado'),
('Z348', 'Supervisión de otros embarazos normales'),
('Z349', 'Supervisión de embarazo normal no especificado'),
('Z359', 'Supervisión de embarazo de alto riesgo, sin otra especificación'),
('Z392', 'Seguimiento postparto, de rutina'),
('Z713', 'Consulta para instrucción y vigilancia de la dieta'),
('Z716', 'Consulta para asesoría sobre el consumo de tabaco'),
('Z719', 'Consulta, no especificada'),
('Z760', 'Consulta para repetición de receta'),
('Z880', 'Historia personal de alergia a penicilina');
